version: "3.8"
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=metrics
    